# Numpy

## ndarray

- 판다스가 데이터프레임을 기반으로한 데이터가공과 분석에 관한 모듈이라면, 넘파이는 <span class="burk">__수학적 연산 및 처리도구__</span>들을 제공하는 모듈입니다.
- 판다스와 넘파이는 데이터분석과 머신러닝분야에서 없어서는 안될 중요모듈입니다.

### import

In [176]:
import numpy as np

### 일반적인 리스트

In [177]:
list1 = [1, 2, 3]
print("list1 : ", list1)
print("list1 type : ", type(list1))

list1 :  [1, 2, 3]
list1 type :  <class 'list'>


### convert list -> ndarray

In [178]:
array1 = np.array(list1)
print("array1 : ", array1)
print("array1 type : ", type(array1))

array1 :  [1 2 3]
array1 type :  <class 'numpy.ndarray'>


### dimension

#### 1차원

In [179]:
array1 = np.array(
    [1, 2, 3]
)
print(array1)
print('array1 : ', type(array1))
print('array1 array 형태 :', array1.shape)
# shape : 행의 갯수와 열의 갯수를 표현해주는 ndarray 속성
# 현재는 1차원 배열을 사용하고 있으므로, 열의 갯수는 공란이 표시

[1 2 3]
array1 :  <class 'numpy.ndarray'>
array1 array 형태 : (3,)


#### 2차원

In [180]:
array2 = np.array(
    [
        [1, 2, 3], 
        [2, 3, 4]
    ]
)
print(array2)
print('array2 : ', type(array2))
print('array2 array 형태 :', array2.shape)

[[1 2 3]
 [2 3 4]]
array2 :  <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)


In [181]:
array3 = np.array(
    [
        [1, 2, 3], 
    ]
)
print(array3)
print('array3 : ', type(array3))
print('array3 array 형태 :', array3.shape)

[[1 2 3]]
array3 :  <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


In [182]:
array4 = np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)
print(array4)

[[1 2]
 [3 4]
 [5 6]]


#### 3차원

In [183]:
array0 = np.array(
    [
        [
            [1, 2],
            [3, 4],
        ],
        [
            [5, 6],
            [7, 8],
        ],
        [
            [9, 10],
            [11, 12],
        ],
    ],
)
print("차원값 : ", array0.ndim)
print("모양 : ", array0.shape)
print(array0)

차원값 :  3
모양 :  (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### 3차원

In [184]:
array0 = np.array(
    [
        [
            [1, 2],
            [3, 4],
        ],
        [
            [5, 6],
            [7, 8],
        ],
        [
            [9, 10],
            [11, 12],
        ],
    ],
)
print("차원값 : ", array0.ndim)
print("모양 : ", array0.shape)
print(array0)

차원값 :  3
모양 :  (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [185]:
array4 = np.array(
    [
        [
            [1, 2, 0],
            [3, 4, 0],
            [3, 4, 0],
        ],
        [
            [5, 6, 0],
            [7, 8, 0],
            [7, 8, 0],
        ],
        [
            [9, 10, 0],
            [11, 12, 0],
            [11, 12, 0],
        ],
        [
            [9, 10, 0],
            [11, 12, 0],
            [11, 12, 0],
        ],
    ],
)
print("차원값 : ", array4.ndim)
print("모양 : ", array4.shape)
print(array4)

차원값 :  3
모양 :  (4, 3, 3)
[[[ 1  2  0]
  [ 3  4  0]
  [ 3  4  0]]

 [[ 5  6  0]
  [ 7  8  0]
  [ 7  8  0]]

 [[ 9 10  0]
  [11 12  0]
  [11 12  0]]

 [[ 9 10  0]
  [11 12  0]
  [11 12  0]]]


### ndim
- .ndim : ndarray의 차원 구성(shape)을 저장하고 있는 속성

In [186]:
print('array1 : {0}차원\narray2 : {1}차원\narray3 : {2}차원\narray0 : {3}차원'.format(array1.ndim, array2.ndim, array3.ndim, array0.ndim))

array1 : 1차원
array2 : 2차원
array3 : 2차원
array0 : 3차원


### dtype
- .dtype이 갖는 값은 ndarray구성에 따라 달라집니다.
    -  정수 + 문자 : <U11
    -  정수 + 실수 + 문자 : <U32
    -  문자 : <U2
-  정수와 실수가 array에 섞이면 모든 데이터가 실수로 변환

In [187]:
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'numpy.ndarray'>
[1 2 3] int32


In [188]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print('배열의 값', array2, ' 배열의 데이터 타입', array2.dtype)

배열의 값 ['1' '2' 'test']  배열의 데이터 타입 <U11


In [189]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print('배열의 값', array3, '\t 배열의 타입', array3.dtype)

배열의 값 [1. 2. 3.] 	 배열의 타입 float64


### astype

In [190]:
array_int = np.array([1, 2, 3])

# 정수 -> 실수
array_float = array_int.astype('float64')
print('정수->실수 : 배열의 값', array_float, '\t\t배열의 데이터 타입', array_float.dtype)

# 실수 -> 정수
array_int = array_float.astype('int32')
print('실수->정수 : 배열의 값', array_int, '\t\t\t배열의 데이터 타입', array_int.dtype)

# 정수 -> 문자
array_str = array_int.astype('str')
print('정수->문자 : 배열의 값', array_str, '\t\t배열의 데이터 타입', array_str.dtype)

# 실수 -> 문자
array_str = array_float.astype('str')
print('실수->문자 : 배열의 값', array_str, '\t배열의 데이터 타입', array_str.dtype)

# 문자 -> 정수
array_int = array_str.astype('float64').astype('int32')
print('문자->정수 : 배열의 값', array_int, '\t\t\t배열의 데이터 타입', array_int.dtype)

# 문자 -> 실수
array_float = array_str.astype('float64')
print('문자->실수 : 배열의 값', array_float, '\t\t배열의 데이터 타입', array_float.dtype)

정수->실수 : 배열의 값 [1. 2. 3.] 		배열의 데이터 타입 float64
실수->정수 : 배열의 값 [1 2 3] 			배열의 데이터 타입 int32
정수->문자 : 배열의 값 ['1' '2' '3'] 		배열의 데이터 타입 <U11
실수->문자 : 배열의 값 ['1.0' '2.0' '3.0'] 	배열의 데이터 타입 <U32
문자->정수 : 배열의 값 [1 2 3] 			배열의 데이터 타입 int32
문자->실수 : 배열의 값 [1. 2. 3.] 		배열의 데이터 타입 float64


### axis
- axis = 0은 행끼리 연산
- axis = 1은 열끼리 연산

In [191]:
array2 = np.array(
    [
        [1, 2, 3],
        [2, 3, 4],
    ],
)
print(array2)
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

[[1 2 3]
 [2 3 4]]
15
[3 5 7]
[6 9]


### ndarray 다양한 생성법

#### arange

In [192]:
sequence_array = np.arange(2, 10, 2) # start, end+1, step
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[2 4 6 8]
int32 (4,)


#### zeros

In [193]:
zero_array = np.zeros((3, 2)) # dtype 파라미터사용시 원하는 타입 지정 default float64
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)


#### ones

In [194]:
one_array = np.ones((3, 2))  # dtype 파라미터사용시 원하는 타입 지정 default float64
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape
- ndarray의 shape을 변경
- 변환가능한 구조여야함.(오류발생)

In [195]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### reshape입력값 중 -1을 줄경우

In [196]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shaspe: ', array2.shape)
print('array2 :\n', array2)

array3 = array1.reshape(5, -1)
print('array3 shaspe: ', array3.shape)
print('array3 :\n ', array3)

n = 5
array1 = np.arange(100)
array4 = array1.reshape(n, -1)
print('array4 shape : ', array4.shape)
print('array4 : \n', array4)

[0 1 2 3 4 5 6 7 8 9]
array2 shaspe:  (2, 5)
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shaspe:  (5, 2)
array3 :
  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4 shape :  (5, 20)
array4 : 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


####  (-1, 1)

In [197]:
array1 = np.arange(5)

array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape : ", array2d_1.shape)
print("array2d_1 : \n", array2d_1)

array2d_1 shape :  (5, 1)
array2d_1 : 
 [[0]
 [1]
 [2]
 [3]
 [4]]


####  (-1,) : 1차원으로 변환

In [198]:
array1 = np.arange(5)

array2d_1 = array1.reshape(-1,)
print("array2d_1 shape : ", array2d_1.shape)
print("array2d_1 : \n", array2d_1)

array2d_1 shape :  (5,)
array2d_1 : 
 [0 1 2 3 4]


### Indexing
- 특정 위치의 단일값 추출

In [199]:
array1 = np.arange(start=1, stop=10) # 1~9
print('array1 : ', array1)

# index는 0부터 시작하므로 array1[2]는 세번째 index위치의 데이터 값을 의미
value = array1[2]
print('value : ', value)
print(type(value))
print('뒤에서 첫번째 값 : ', array1[-1], ', 뒤에서 두번째 값 : ', array1[-2])

array1 :  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>
뒤에서 첫번째 값 :  9 , 뒤에서 두번째 값 :  8


In [200]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)
print('(row=0, col=0) index 가리키는 값 : ', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값 : ', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값 : ', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값 : ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값 :  1
(row=0, col=1) index 가리키는 값 :  2
(row=1, col=0) index 가리키는 값 :  4
(row=2, col=2) index 가리키는 값 :  9


### Slicing

In [201]:
array1 = np.arange(start=1, stop=10)
print(array1)

print('-'*100)

array3 = array1[0:3]
print(array3)
print(type(array3))

print('-'*100)

prray4 = array1[:3]
print(array4)

print('-'*100)

array5 = array1[3:]
print(array5)

print('-'*100)

array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]
----------------------------------------------------------------------------------------------------
[1 2 3]
<class 'numpy.ndarray'>
----------------------------------------------------------------------------------------------------
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
----------------------------------------------------------------------------------------------------
[4 5 6 7 8 9]
----------------------------------------------------------------------------------------------------
[1 2 3 4 5 6 7 8 9]


In [202]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d: \n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [203]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print('array3\n', array3)
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 2], 0:2]
print('array4=n', array4)
print('array2d[[0, 2], 0:2] -> ', array4.tolist())

array5 = array2d[[0, 1]]
print('array5\n', array5)
print('array2d[[0,1]] =>', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array3
 [3 6]
array2d[[0, 1], 2] =>  [3, 6]
array4=n [[1 2]
 [7 8]]
array2d[[0, 2], 0:2] ->  [[1, 2], [7, 8]]
array5
 [[1 2 3]
 [4 5 6]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


### Boolean Indexing

In [204]:
array1d = np.arange(start=1, stop=10)
print(array1d)
print(array1d > 5)
var1 = array1d > 5
print("var1:", var1)
print(type(var1))
print(var1.dtype)

# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 boolean indexing result : ', array3)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>
bool
array1d > 5 boolean indexing result :  [6 7 8 9]


### Indexing By Value

In [205]:
print(array1d)

indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print("일반 인덱스로 필터링한 결과 : ", array4)

[1 2 3 4 5 6 7 8 9]
일반 인덱스로 필터링한 결과 :  [6 7 8 9]


### sort()

In [206]:
org_array = np.array([3, 1, 9, 5])
print("원본 행렬 : ", org_array)

sort_array1 = np.sort(org_array)
print("np.sort() 반환 : ", sort_array1)
print("np.sort() 원본 : ", org_array)

원본 행렬 :  [3 1 9 5]
np.sort() 반환 :  [1 3 5 9]
np.sort() 원본 :  [3 1 9 5]


In [207]:
sort_array2 = org_array.sort()
print("org_array() 반환 : ", sort_array2)
print("org_array() 원본 : ", org_array)

org_array() 반환 :  None
org_array() 원본 :  [1 3 5 9]


In [208]:
sort_array1_desc = np.sort(org_array)[::-1]
print("내림차순으로 정렬 : ", sort_array1_desc)

내림차순으로 정렬 :  [9 5 3 1]


In [209]:
array2d = np.array( # 2차원 배열의 정렬
    [
        [8, 12],
        [9, 1],
    ],
)
print("origin : \n", array2d)
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print("행 정렬 : \n", sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis = 1)
print("열 정렬 : \n", sort_array2d_axis1)

origin : 
 [[ 8 12]
 [ 9  1]]
행 정렬 : 
 [[ 8  1]
 [ 9 12]]
열 정렬 : 
 [[ 8 12]
 [ 1  9]]


In [211]:
array3d = np.array( # 3차원 배열의 정렬
    [
        [
            [8, 7],
            [3, 1],
        ],
        [
            [9, 6],
            [7, 5],
        ],
        [
            [7, 3],
            [11, 12],
        ],
    ],
)
print("origin : \n", array3d)
sort_array3d_axis0 = np.sort(array3d, axis = 0)
print("axis=0 정렬 : \n", sort_array3d_axis0)
sort_array3d_axis1 = np.sort(array3d, axis = 1)
print("axis=1 정렬 : \n", sort_array3d_axis1)
sort_array3d_axis2 = np.sort(array3d, axis = 2)
print("axis=2 정렬 : \n", sort_array3d_axis2)

origin : 
 [[[ 8  7]
  [ 3  1]]

 [[ 9  6]
  [ 7  5]]

 [[ 7  3]
  [11 12]]]
axis=0 정렬 : 
 [[[ 7  3]
  [ 3  1]]

 [[ 8  6]
  [ 7  5]]

 [[ 9  7]
  [11 12]]]
axis=1 정렬 : 
 [[[ 3  1]
  [ 8  7]]

 [[ 7  5]
  [ 9  6]]

 [[ 7  3]
  [11 12]]]
axis=2 정렬 : 
 [[[ 7  8]
  [ 1  3]]

 [[ 6  9]
  [ 5  7]]

 [[ 3  7]
  [11 12]]]


### argsort()

In [219]:
org_array = np.array([3, 1, 9, 5])
print("일반 sort 결과 : ", np.sort(org_array))

sort_index = np.argsort(org_array)
print('argsort 결과의 데이터 타입 : ', type(sort_index))
print('argsort 의 결과 : ', sort_index)
print("argsort의 결과중 가장 마지막값을 원본배열의 인덱싱값으로 사용 (가장큰값):", org_array[sort_index[-1]])

일반 sort 결과 :  [1 3 5 9]
argsort 결과의 데이터 타입 :  <class 'numpy.ndarray'>
argsort 의 결과 :  [1 0 3 2]
argsort의 결과중 가장 마지막값을 원본배열의 인덱싱값으로 사용 (가장큰값): 9


In [231]:
org_array = np.array([3, 1, 9, 5])
sort_index_desc = np.argsort(org_array)[::-1]
print('argsort로 원본 인덱싱')
print("sort_index_desc : \n", sort_index_desc)

argsort로 원본 인덱싱
sort_index_desc : 
 [2 3 0 1]


In [226]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([98, 95, 84, 98, 88])

sort_index = np.argsort(score_array)[::-1]
print("sort index: ", sort_index)
print("최고점자 이름 : ", name_array[sort_index[0]])

# 정렬 결과 전체
name_array_sort = name_array[sort_index]
score_array_sort = score_array[sort_index]
print(name_array_sort)
print(score_array_sort)

sort index:  [3 0 1 4 2]
최고점자 이름 :  Kate
['Kate' 'John' 'Mike' 'Samuel' 'Sarah']
[98 98 95 88 84]
