# Setting

In [588]:
import sklearn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [589]:
import pandas as pd

# load

In [590]:
iris = load_iris()

In [591]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# Preprocessing

## Ready DataFrame by data

### Feature & Target

#### Feature Data

In [592]:
iris.data # feature

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

#### Feature Names

In [593]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

#### Target data

In [594]:
iris.target # 결정값

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#### Target Names

In [595]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## Make DataFrame By Feature & Target

In [596]:
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)

In [597]:
iris_df['label'] = iris.target

In [598]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

## Ready Train & Test Value
- train : X_train -> Y_train
- test : X_test -> Y_test

In [599]:
X_train, X_test, Y_train,Y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=11)
# iris.data : 전체 Feature
# iris.target : 전체 target
# test_size = 0.2 : 테스트 데이터 수량 비율 - 현재 150이므로 테스트 데이터는 30건
# random_state : 랜덤 시드값. 랜덤하게 골라진 데이터로 분리되는데 관여하는 임의 설정값

# Model

## Load DecisionTree

In [600]:
from sklearn.tree import DecisionTreeClassifier

## Instance Model

In [601]:
dt_clf = DecisionTreeClassifier(random_state=11)

# Train

In [602]:
dt_clf.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=11)

# Predict

In [603]:
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [604]:
k = 0
for i in pred :
    if pred[i] == 0 :
        result = "setosa"
    elif pred[i] == 1 :
        result = "versicolor"
    elif pred[i] == 2:
        result = "virsinica"
        
    print(X_test[k], " : ", result)
    k = k + 1

[6.8 3.  5.5 2.1]  :  versicolor
[6.7 3.  5.2 2.3]  :  versicolor
[6.3 2.8 5.1 1.5]  :  virsinica
[6.3 3.3 4.7 1.6]  :  virsinica
[6.4 2.7 5.3 1.9]  :  versicolor
[4.9 3.1 1.5 0.1]  :  virsinica
[6.7 3.1 4.4 1.4]  :  virsinica
[5.7 4.4 1.5 0.4]  :  virsinica
[4.8 3.1 1.6 0.2]  :  virsinica
[6.1 2.9 4.7 1.4]  :  virsinica
[6.  2.2 5.  1.5]  :  virsinica
[6.  2.2 4.  1. ]  :  virsinica
[5.4 3.  4.5 1.5]  :  virsinica
[5.7 2.5 5.  2. ]  :  versicolor
[6.9 3.1 5.4 2.1]  :  versicolor
[4.5 2.3 1.3 0.3]  :  virsinica
[6.3 2.9 5.6 1.8]  :  versicolor
[5.6 3.  4.5 1.5]  :  virsinica
[6.5 3.2 5.1 2. ]  :  versicolor
[5.8 2.7 5.1 1.9]  :  versicolor
[5.6 2.5 3.9 1.1]  :  virsinica
[4.7 3.2 1.3 0.2]  :  virsinica
[4.6 3.6 1.  0.2]  :  virsinica
[6.4 3.2 4.5 1.5]  :  virsinica
[4.8 3.  1.4 0.1]  :  virsinica
[4.8 3.4 1.6 0.2]  :  virsinica
[5.9 3.  5.1 1.8]  :  versicolor
[6.6 3.  4.4 1.4]  :  virsinica
[5.4 3.9 1.3 0.4]  :  virsinica
[6.  3.4 4.5 1.6]  :  virsinica


In [605]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [606]:
Y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

# Valid

In [607]:
from sklearn.metrics import accuracy_score

result = accuracy_score(Y_test, pred)
print('예측 정확도 : {0:.4f}'.format(result))

예측 정확도 : 0.9333


# Custom Train

In [608]:
pred = dt_clf.predict(np.array([[4,4,5,5]]))

for i in pred :
    if i == 0 :
        result = "setosa"
    elif i == 1 :
        result = "versicolor"
    elif i == 2:
        result = "virsinica"
        
    print("[4,4,5,5] : ", result)

[4,4,5,5] :  virsinica
