# Ready

## Import

In [827]:
import numpy as np
import pandas as pd
import math

## Check

# Preprocessing

### Ready Target

In [828]:
df = pd.read_csv('../../02_DataAnalysis/titanic_train.csv')

df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

#### Missing Data

##### Missing Data check

In [829]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

##### Missing Data fill

In [830]:
df.Age.fillna(df.Age.mean(), inplace=True)
df.Cabin.fillna('N', inplace=True)
df.Embarked.fillna('N', inplace=True)

##### Missing Data check

In [831]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [832]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     N        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250     N        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500     N        S

#### Label Encoding

- Cabin
- Sex
- Embarked

##### Cabin 첫글자만 취급

In [833]:
df['Cabin'] = df['Cabin'].str[:1] # Cabin 첫글자만 적용
df['Cabin'].value_counts() # 확인

N    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: Cabin, dtype: int64

In [834]:
from sklearn.preprocessing import LabelEncoder

for columnName in ['Cabin', 'Sex', 'Embarked'] :
    encoder = LabelEncoder()
    encoded = encoder.fit_transform(df[columnName])
    df[columnName] = encoded
    print(":"*50 + columnName)
    print(df[columnName].value_counts())

::::::::::::::::::::::::::::::::::::::::::::::::::Cabin
7    687
2     59
1     47
3     33
4     32
0     15
5     13
6      4
8      1
Name: Cabin, dtype: int64
::::::::::::::::::::::::::::::::::::::::::::::::::Sex
1    577
0    314
Name: Sex, dtype: int64
::::::::::::::::::::::::::::::::::::::::::::::::::Embarked
3    644
0    168
2     77
1      2
Name: Embarked, dtype: int64


In [835]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare  Cabin  Embarked  
0         A/5 21171   7.2500      7         3  
1          PC 17599  71.2833      2         0  
2  STON/O2. 3101282   7.9250      7         3  
3            113803  53.1000      2         3  
4            373450   8.0500      7         3

#### Drop Columns

In [836]:
print('Before Drop')
print(df.columns)
df = df.drop(labels=['PassengerId', 'Name', 'Ticket'], axis=1)
print('After Drop')
print(df.columns)

Before Drop
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
After Drop
Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin',
       'Embarked'],
      dtype='object')


#### After Preprocessing Data 

- Survived	Pclass	Sex	Age	SibSp	Parch	Fare	Cabin	Embarked

In [837]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0         0       3    1  22.0      1      0   7.2500      7         3
1         1       1    0  38.0      1      0  71.2833      2         0
2         1       3    0  26.0      0      0   7.9250      7         3
3         1       1    0  35.0      1      0  53.1000      2         3
4         0       3    1  35.0      0      0   8.0500      7         3

# Learning

## Import

In [838]:
from sklearn.model_selection import train_test_split

## Divide train & target At DF

In [839]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin',
       'Embarked'],
      dtype='object')

In [840]:
train = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin','Embarked']]
target = df['Survived']

In [841]:
train.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0       3    1  22.0      1      0   7.2500      7         3
1       1    0  38.0      1      0  71.2833      2         0
2       3    0  26.0      0      0   7.9250      7         3
3       1    0  35.0      1      0  53.1000      2         3
4       3    1  35.0      0      0   8.0500      7         3

In [842]:
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

## split Data

In [843]:
X_train, X_test, Y_train,Y_test = train_test_split(train, target, test_size=0.2, random_state=15)

## Estimator

### Import

In [844]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

dtc = DecisionTreeClassifier()
rfc = RandomForestClassifier()
lr = LogisticRegression()

#### DecisionTreeClassifier

In [845]:
dtc.fit(X_train, Y_train)
dtc_pred = dtc.predict(X_test)
dtc_result = accuracy_score(Y_test, dtc_pred)
print('DecisionTreeClassifier : {0:.4f}%'.format(dtc_result*100))

DecisionTreeClassifier : 74.8603%


#### RandomForestClassifier

In [846]:
rfc.fit(X_train, Y_train)
rfc_pred = rfc.predict(X_test)
rfc_result = accuracy_score(Y_test, rfc_pred)
print('RandomForestClassifier : {0:.4f}%'.format(rfc_result*100))

RandomForestClassifier : 78.2123%


#### LogisticRegression

In [847]:
lr.fit(X_train, Y_train)
lr_pred = lr.predict(X_test)
lr_result = accuracy_score(Y_test, lr_pred)
print('LogisticRegression : {0:.4f}%'.format(lr_result*100))

LogisticRegression : 79.3296%


c:\users\java01\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [848]:
X_test[0:1]

Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
310       1    0  24.0      0      0  83.1583      2         0

In [849]:
dtc.predict(X_test[0:1])

array([1], dtype=int64)

In [850]:
rfc.predict(X_test[0:1])

array([1], dtype=int64)

In [851]:
lr.predict(X_test[0:1])

array([1], dtype=int64)

In [852]:
lr_pred_reshape = lr_pred.reshape(-1, 1) # Logistic Regress모델의 예측 결과들을 1열모양으로 재배치

In [853]:
X_test['survived_lr'] = lr_pred_reshape
X_test['survived_lr'] = X_test['survived_lr'].apply(
    lambda x : '생존' if x == 1 else '사망'
)
X_test.head(10)

<ipython-input-853-f4230b1425ef>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['survived_lr'] = lr_pred_reshape
<ipython-input-853-f4230b1425ef>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['survived_lr'] = X_test['survived_lr'].apply(


Pclass  Sex        Age  SibSp  Parch      Fare  Cabin  Embarked  \
310       1    0  24.000000      0      0   83.1583      2         0   
635       2    0  28.000000      0      0   13.0000      7         3   
44        3    0  19.000000      0      0    7.8792      7         2   
698       1    1  49.000000      1      1  110.8833      2         0   
750       2    0   4.000000      1      1   23.0000      7         3   
837       3    1  29.699118      0      0    8.0500      7         3   
144       2    1  18.000000      0      0   11.5000      7         3   
169       3    1  28.000000      0      0   56.4958      7         3   
166       1    0  29.699118      0      1   55.0000      4         3   
660       1    1  50.000000      2      0  133.6500      7         3   

    survived_lr  
310          생존  
635          생존  
44           생존  
698          사망  
750          생존  
837          사망  
144          사망  
169          사망  
166          생존  
660          사망

In [854]:
X_test.drop(['survived_lr'], axis=1, inplace=True)

c:\users\java01\appdata\local\programs\python\python38\lib\site-packages\pandas\core\frame.py:4305: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


# KFold

# 폴드 세트를 5개로 하여 각 세트마다의 정확도와 정확도의 평균을 출력하세요

### load data

In [855]:
features = df.drop(labels='Survived', axis=1).values
target = df['Survived']

In [856]:
features

array([[ 3.        ,  1.        , 22.        , ...,  7.25      ,
         7.        ,  3.        ],
       [ 1.        ,  0.        , 38.        , ..., 71.2833    ,
         2.        ,  0.        ],
       [ 3.        ,  0.        , 26.        , ...,  7.925     ,
         7.        ,  3.        ],
       ...,
       [ 3.        ,  0.        , 29.69911765, ..., 23.45      ,
         7.        ,  3.        ],
       [ 1.        ,  1.        , 26.        , ..., 30.        ,
         2.        ,  0.        ],
       [ 3.        ,  1.        , 32.        , ...,  7.75      ,
         7.        ,  2.        ]])

In [857]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

### Train & Predict & Accuracy IF n_splits=5

In [858]:
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [859]:
features

array([[ 3.        ,  1.        , 22.        , ...,  7.25      ,
         7.        ,  3.        ],
       [ 1.        ,  0.        , 38.        , ..., 71.2833    ,
         2.        ,  0.        ],
       [ 3.        ,  0.        , 26.        , ...,  7.925     ,
         7.        ,  3.        ],
       ...,
       [ 3.        ,  0.        , 29.69911765, ..., 23.45      ,
         7.        ,  3.        ],
       [ 1.        ,  1.        , 26.        , ..., 30.        ,
         2.        ,  0.        ],
       [ 3.        ,  1.        , 32.        , ...,  7.75      ,
         7.        ,  2.        ]])

In [860]:
kfold = KFold(n_splits=5) # n개의 데이터세트로 분리하는 KFold 객체 생성
cv_accuracy = [] # 세트별로 계산된 정확도들을 보관할 리스트

dtc = DecisionTreeClassifier()

c = 0
for train_index, test_index in kfold.split(features) :
    c += 1
    
    # Get Data
    X_train, X_test = features[train_index], features[test_index]
    Y_train, Y_test = target[train_index], target[test_index]
    
    # Train
    dtc.fit(X_train, Y_train)
    
    # Predict
    pred = dtc.predict(X_test)
    
    # Accuracy
    accuracy = accuracy_score(Y_test, pred)
    
    # for report    
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    
    # 정확도, 학습데이터 수, 테스트데이터 수 순으로 확인
    print('#{0}번째 kfold의 정확도 : {1:.3f}, 학습데이터수 : {2}, 테스트데이터수 : {3}'.format(c, accuracy, train_size, test_size))
    
    # 세트별로 계산된 정확도들을 보관할 리스트에 저장
    cv_accuracy.append(accuracy)
    
print("### 평균 검증 정확도 : ", np.mean(cv_accuracy))

#1번째 kfold의 정확도 : 0.743, 학습데이터수 : 712, 테스트데이터수 : 179
#2번째 kfold의 정확도 : 0.775, 학습데이터수 : 713, 테스트데이터수 : 178
#3번째 kfold의 정확도 : 0.787, 학습데이터수 : 713, 테스트데이터수 : 178
#4번째 kfold의 정확도 : 0.775, 학습데이터수 : 713, 테스트데이터수 : 178
#5번째 kfold의 정확도 : 0.831, 학습데이터수 : 713, 테스트데이터수 : 178
### 평균 검증 정확도 :  0.7823112171238465
