In [2]:
import numpy as np
from sklearn.base import BaseEstimator
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_digits

In [5]:
digits = load_digits()
print(digits.data)
print("### digits.data.shape : ", digits.data.shape)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
### digits.data.shape :  (1797, 64)


In [6]:
k = 0
for i in digits.data[0] :
    print("%2.0f" % i, end='')
    k += 1
    if k % 8 == 0: print()

 0 0 513 9 1 0 0
 0 013151015 5 0
 0 315 2 011 8 0
 0 412 0 0 8 8 0
 0 5 8 0 0 9 8 0
 0 411 0 112 7 0
 0 214 51012 0 0
 0 0 61310 0 0 0


In [8]:

print("### digits.target.shape: ", digits.target.shape)
for i in digits.target :
    print(i, end='')

### digits.target.shape:  (1797,)
012345678901234567890123456789095565098984177351002278201263373346664915095282001763217463139176843140536961754472822579548849089801234567890123456789012345678909556509898417735100227820126337334666491509528200176321731391768431405369617544728225548849089801234567890123456789012345678909556509898417735100227820126337334666491509528200176321746313917684314053696175447282257954884908930123456789012345678901234567890955650989841773510022782012633733466649150952820017632174631391768431405369617544728225795488490898012345678901234567890123456789095565098984177351002278201263373346664915095282001763217463139176843140536961754472822579548849089801234567890123456789012345678909556509898417735100227820126337334666491509528200176321746313917684314053696175447282257954884908980123456789012345678901234567890955650989841773510022782012633733466649150952820017632174631391768431405369617544728225795488490898123456789012345678901234567890955650989841773512782012633733

In [13]:
class MyFakeClassifier(BaseEstimator) : # BaseEstimator 상속
    def fit(self, X, Y): # X_train, Y_train
        pass # 내가만든 머신러닝 알고리즘의 fit은 하는일이 없습니다.
    
    def predict(self, X) : # X_test
        
        return np.zeros((len(X), 1), dtype=bool)
    # 리턴값 -> pred, 추후 y_test와 비교되어 정확도 계산
        

In [16]:
# digits번호가 7이면 True, astype(int)로 1로 변환
# 7이 아니면 False고 0으로 변환
y = (digits.target == 7).astype(int)
# for i in y :
#     print(i, end='')

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, y, test_size=0.2)

In [21]:
fakeclf = MyFakeClassifier() # 객체 생성
fakeclf.fit(X_train, Y_train) # 학습 : pass
fakepred = fakeclf.predict(X_test) # 예측 : 모두 0으로 된 배열 리턴