In [78]:
import numpy as np
from sklearn.base import BaseEstimator
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_digits

In [79]:
digits = load_digits()
print(digits.data)
print("### digits.data.shape : ", digits.data.shape)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
### digits.data.shape :  (1797, 64)


In [80]:
k = 0
for i in digits.data[0] :
    print("%2.0f" % i, end='')
    k += 1
    if k % 8 == 0: print()

 0 0 513 9 1 0 0
 0 013151015 5 0
 0 315 2 011 8 0
 0 412 0 0 8 8 0
 0 5 8 0 0 9 8 0
 0 411 0 112 7 0
 0 214 51012 0 0
 0 0 61310 0 0 0


In [81]:

print("### digits.target.shape: ", digits.target.shape)
for i in digits.target :
    print(i, end='')

### digits.target.shape:  (1797,)
012345678901234567890123456789095565098984177351002278201263373346664915095282001763217463139176843140536961754472822579548849089801234567890123456789012345678909556509898417735100227820126337334666491509528200176321731391768431405369617544728225548849089801234567890123456789012345678909556509898417735100227820126337334666491509528200176321746313917684314053696175447282257954884908930123456789012345678901234567890955650989841773510022782012633733466649150952820017632174631391768431405369617544728225795488490898012345678901234567890123456789095565098984177351002278201263373346664915095282001763217463139176843140536961754472822579548849089801234567890123456789012345678909556509898417735100227820126337334666491509528200176321746313917684314053696175447282257954884908980123456789012345678901234567890955650989841773510022782012633733466649150952820017632174631391768431405369617544728225795488490898123456789012345678901234567890955650989841773512782012633733

In [82]:
class MyFakeClassifier(BaseEstimator) : # BaseEstimator 상속
    def fit(self, X, Y): # X_train, Y_train
        pass # 내가만든 머신러닝 알고리즘의 fit은 하는일이 없습니다.
    
    def predict(self, X) : # X_test
        
        return np.zeros((len(X), 1), dtype=bool)
    # 리턴값 -> pred, 추후 y_test와 비교되어 정확도 계산
        

In [83]:
# digits번호가 7이면 True, astype(int)로 1로 변환
# 7이 아니면 False고 0으로 변환
y = (digits.target == 7).astype(int)
# for i in y :
#     print(i, end='')

In [84]:
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, y, test_size=0.2)

In [85]:
fakeclf = MyFakeClassifier() # 객체 생성
fakeclf.fit(X_train, Y_train) # 학습 : pass
fakepred = fakeclf.predict(X_test) # 예측 : 모두 0으로 된 배열 리턴

In [86]:
print(fakepred)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 

In [87]:
# MyFakeClassifier의 predict 결과는 모두 0
# Y_test값은 실제값이 7일 때만 1, 나머지 모두 0
acc = accuracy_score(Y_test, fakepred)
print('모든 예측을 0으로 하여도 정확도는 {:.3f}'.format(acc))

모든 예측을 0으로 하여도 정확도는 0.875


# Confusion Matrix(오차행렬)

> 기계 학습 분야의 통계적 분류 같은 문제에서 컨퓨전 행렬이란 지도 학습으로 훈련된 분류 알고리즘의 성능을 시각화 할 수있는 표이다.
행렬의 각 행은 예측 된 클래스의 인스턴스를 나타내며 각 열은 실제 클래스의 인스턴스를 나타낸다 (또는 그 반대).컨퓨전이라는 이름은 시스템이 두 개의 클래스를 얼마나 헷갈려 하는지를 쉽게 알 수 있다는 사실에서 유래되었다.

In [88]:
from sklearn.metrics import confusion_matrix

# 앞절의 예측 결과인 fakepred와 실제 결과인 y_test의 Confusion Matrix 출력
confusion_matrix(Y_test, fakepred)

array([[315,   0],
       [ 45,   0]], dtype=int64)

In [89]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
print("정밀도 : ", precision_score(Y_test, fakepred))
print("재현율 : ", recall_score(Y_test, fakepred))


정밀도 :  0.0
재현율 :  0.0


c:\users\java01\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [90]:
# y_test값과 pred값을 전달인수로 넣어서 정확도, 오차행렬, 정밀도, 재현율을 계산하고 출력하는 함수 제작

In [91]:
def get_clf_eval(y_test, pred) :
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    
    print("오차행렬")
    print(confusion)
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}'.format(accuracy, precision, recall))

In [92]:
# 원본 데이터를 재로딩, 데이터셋(피쳐와 타겟)분할, 데이터 가공
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

In [93]:
def transeform_feature(df) :
    # Missing Data
    df['Age'].fillna(df['Age'].mean(), inplace=True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0, inplace=True)
    
    # Drop Column
    df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
    
    # Encoding
    df['Cabin'] = df['Cabin'].str[:1]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features :
        le = LabelEncoder()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
    return df

In [94]:
titanic_df = pd.read_csv('../../02_DataAnalysis/titanic_train.csv')
targetColumn = "Survived"
Y_titanic_df = titanic_df[targetColumn]
X_titanic_df = titanic_df.drop(targetColumn, axis=1)
X_titanic_df = transeform_feature(X_titanic_df)

X_train, X_test, Y_train, Y_test = train_test_split(X_titanic_df, Y_titanic_df, test_size=0.2, random_state=11)

In [95]:
rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)
pred = rfc.predict(X_test)
get_clf_eval(Y_test, pred)
# 정밀도와 재현율은 그 둘의 값중 하나가 높아지면 하나가 낮아지는 상관관계에 있기때문에 비슷한 값이 구성되었을 때 높은 성능이라고 평가합니다.

오차행렬
[[106  12]
 [ 15  46]]
정확도: 0.8492, 정밀도: 0.7931, 재현율: 0.7541


In [96]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, Y_train)
pred = dtc.predict(X_test)
get_clf_eval(Y_test, pred)
# 정밀도와 재현율은 그 둘의 값중 하나가 높아지면 하나가 낮아지는 상관관계에 있기때문에 비슷한 값이 구성되었을 때 높은 성능이라고 평가합니다.

오차행렬
[[99 19]
 [17 44]]
정확도: 0.7989, 정밀도: 0.6984, 재현율: 0.7213


In [97]:
lr = LogisticRegression()
lr.fit(X_train, Y_train)
pred = lr.predict(X_test)
get_clf_eval(Y_test, pred)
# 정밀도와 재현율은 그 둘의 값중 하나가 높아지면 하나가 낮아지는 상관관계에 있기때문에 비슷한 값이 구성되었을 때 높은 성능이라고 평가합니다.

오차행렬
[[104  14]
 [ 13  48]]
정확도: 0.8492, 정밀도: 0.7742, 재현율: 0.7869


c:\users\java01\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## predict_proba() 메소드 확인
- predict_prova : 0과 1을 선택하는 기준을 확률로 표시한 배열

In [98]:
pred_proba = lr.predict_proba(X_test)
print('pred_proba array에서 앞 3개만 샘플로 추출 : \n', pred_proba[:3])

pred_proba array에서 앞 3개만 샘플로 추출 : 
 [[0.46175211 0.53824789]
 [0.87863924 0.12136076]
 [0.87717092 0.12282908]]


In [99]:
# Binarizer : 임계값 변형 도구
from sklearn.preprocessing import Binarizer

In [100]:
# threshold : Binarizer의 임계값의 기준이 되는 값을 저장한 변수로 활용.
# 이값보다 작으면 0을 크면 1을 반환
X = [
    [1, -1, 2],
    [2, 0, 0],
    [0, 1.1, 1.2]
]
binarizer = Binarizer(threshold=1.1)
print(binarizer.fit_transform(X))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


## 분류 결정 임계값 0.5기반에서 Binarizer를 이용하여 예측값 변환

In [101]:
pred_proba = lr.predict_proba(X_test)
pred_proba_1 = pred_proba[:, 1].reshape(-1, 1)
print(pred_proba_1)
binarizer = Binarizer(threshold=0.5)
binarizer.fit(pred_proba_1)
custom_predict = binarizer.transform(pred_proba_1)
get_clf_eval(Y_test, custom_predict)

[[0.53824789]
 [0.12136076]
 [0.12282908]
 [0.11730706]
 [0.14471027]
 [0.11774233]
 [0.11161228]
 [0.79117088]
 [0.21709221]
 [0.6306465 ]
 [0.10017236]
 [0.12502264]
 [0.12283511]
 [0.11165858]
 [0.56352896]
 [0.14106496]
 [0.09626215]
 [0.26655139]
 [0.27520975]
 [0.82820508]
 [0.24636982]
 [0.38070654]
 [0.14543006]
 [0.18514805]
 [0.11203246]
 [0.23445307]
 [0.14030802]
 [0.07414516]
 [0.28037989]
 [0.30448184]
 [0.94725314]
 [0.81744533]
 [0.12677781]
 [0.82606966]
 [0.39929127]
 [0.23445307]
 [0.07239623]
 [0.61121278]
 [0.05293635]
 [0.10394781]
 [0.35050439]
 [0.08335452]
 [0.82184592]
 [0.70772506]
 [0.63056078]
 [0.6305772 ]
 [0.91891158]
 [0.35872277]
 [0.94885769]
 [0.11206729]
 [0.59301267]
 [0.11165858]
 [0.13283413]
 [0.72520926]
 [0.30930873]
 [0.19696528]
 [0.22627228]
 [0.12283013]
 [0.15425586]
 [0.43218691]
 [0.28008564]
 [0.10077886]
 [0.54554871]
 [0.51359943]
 [0.44421615]
 [0.09462614]
 [0.66696692]
 [0.59430053]
 [0.95184001]
 [0.14806889]
 [0.12891671]
 [0.16

In [102]:
pred_proba_1 = pred_proba[:, 1].reshape(-1, 1)
binarizer = Binarizer(threshold=0.6).fit(pred_proba_1)
custom_predict = binarizer.transform(pred_proba_1)
get_clf_eval(Y_test, custom_predict)

오차행렬
[[112   6]
 [ 16  45]]
정확도: 0.8771, 정밀도: 0.8824, 재현율: 0.7377
