In [27]:
# split() : 괄호안에 지정한 문자를 기준으로 문자열을 분해
# 아무것도 지정하지 않고, 괄호만 있으면 공백(SpaceBar)를 기준으로 분해
# 결과는 리스트 형태로 리턴
string = "The quick brown fox jumps over the lazy dog."
string_list = string.split()
print(string_list)

['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog.']


In [28]:
# print문의 출력 양식 지정 두가지
print("%2dx%2d=%2d" % (6, 3, 6*3))
print("{0:2d}x{1:2d}={2:2d}".format(6, 3, 6*3))

 6x 3=18
 6x 3=18


In [29]:
# 날짜 데이터
from datetime import date, time, datetime, timedelta

In [30]:
# 오늘 날짜를 얻어서 변수에 저장
today = date.today()
print("today: {0!s}".format(today)) # today 값 오늘 날짜
print("year: {0!s}".format(today.year)) # 년
print("month: {0!s}".format(today.month)) # 월
print("day: {0!s}".format(today.day)) # 일

today: 2021-03-02
year: 2021
month: 3
day: 2


In [31]:
# 시간 데이터를 따로 다루는 경우도 있지만, 시간데이터를 다룰 때는 보통
# datetime을 이용하여 시간과 날짜를 한번에 쓰는 경우가 많습니다.
current_datetime = datetime.today() # 현재 시간까지 포함한 오늘날짜 추출
print("날짜시간 : {0!s}".format(current_datetime))
print("시 : {0!s}".format(current_datetime.hour))
print("분 : {0!s}".format(current_datetime.minute))
print("초 : {0!s}".format(current_datetime.second))
# {0!s} : format에 의해 출력으로 전달된 데이터가 문자형이 아니더라도 문자로 출력

날짜시간 : 2021-03-02 14:40:29.250440
시 : 14
분 : 40
초 : 29


In [32]:
# "상대적 날짜 - 1일"이라는 날짜데이터를 생성 -> one_day 변수에 저장
one_day = timedelta(days=-1)
# -1 일을 오늘날짜에 합산하고 그 결과를 yesterday에 저장
yeasterday = today + one_day
# yeasterday 출력
print("yesterday: {0!s}".format(yeasterday))

yesterday: 2021-03-01


In [33]:
# -8 시간 저장
eight_hours = timedelta(hours=-8)
# -8에 대한 day 값과 second 값
print("{0!s}".format(eight_hours.days))
print("{0!s}".format(eight_hours.seconds))
# 60초 * 60분 * 8시간 = 28,800
# 60초 * 60분 * 24시간 = 86,400
# -28,000이라는 시간은 어제의 86,400(24시간) - 28,800(-8시간)
# 출력 : 57,600
# 날짜는 1일전의 날짜

-1
57600


In [34]:
print("{:s}".format(today.strftime('%d/%d/%Y')))
print("{:s}".format(today.strftime('%b %d, %Y')))
print("{:s}".format(today.strftime('%Y-%m-%d')))
print("{:s}".format(today.strftime('%B %d, %Y')))

02/02/2021
Mar 02, 2021
2021-03-02
March 02, 2021


In [35]:
# 반복문의 간단 사용
myData = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 반복실행문의 일반적인 예
copyMyData = []
for x in myData:
    copyMyData.append(x)
print(copyMyData)

# 간단 사용예
copyMyData = [x for x in myData]
# for문 안에 있는 x값을 꺼내어 []로 묶어 리스트로 생성(원본 유지)
print(copyMyData)

# for x in myData : myData 리스트에 있는 값들이 x 변수에 전달되어 반복실행
# 반복실행안에서 실행해야할 내용이 x변수를 이용한 단순연산에 가깝다면,
# 반복 실행 앞에서 x 변수로 연산식을 표현해줍니다.
copyMyData = [x * x for x in myData]
print(copyMyData)
# x*x for x in myData 이 명령의 실행결과는 0, 1, 4, 9 ... 이므로
# 명령의 외부에서 이를 리스트로 만들거나 튜플로 만들거나, 다수의 값으로
# 연산할 수 있는 함수에 적용하고자 하는 동작이 필요합니다.
# 위의 예제는 x*x for x in myData 명령을 []로 감싸서 결과들의 리스트를 생성

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [36]:
# 두배열의 모든 조합
epithets = ['sweet', 'annoying', 'cool', 'grey-eyed']
names = ['john', 'alice', 'james']
epithet_names = [(e, n) for e in epithets for n in names]
for a in epithet_names:
    print(a)

('sweet', 'john')
('sweet', 'alice')
('sweet', 'james')
('annoying', 'john')
('annoying', 'alice')
('annoying', 'james')
('cool', 'john')
('cool', 'alice')
('cool', 'james')
('grey-eyed', 'john')
('grey-eyed', 'alice')
('grey-eyed', 'james')


In [37]:
myData = [[1,2,3], [4,5,6], [7,8,9]]
resultList = [row for row in myData if row[2] > 5]
print(resultList)

listBySum = [row for row in myData if sum(row) < 10] # 각 원소안의 배열합이 10미만인 행만 추출
print(listBySum)

[[4, 5, 6], [7, 8, 9]]
[[1, 2, 3]]


In [38]:
# 딕셔너리 데이터에 조건을 적용한 필터링(간략 for문 사용)
my_dictionary = {'customer1': 7, 'customer2': 9, 'customer3': 11}
# items()함수를 이용하여 키값과 밸류값을 key, value에 차례로 전달
# if 문에 의하여 value값이 8초과인것만 골라서 key: value 구성 후
# {} 딕셔너리로 재구성

my_results = {key: value for key, value in my_dictionary.items() if value > 8}
print(my_results)

{'customer2': 9, 'customer3': 11}


### Pandas
#### import pandas as pd : 데이터 가공처리에 필요한 기능
#### import numpy as np : 수학적인 처리에 필요한 기능
- as 뒤의 단어는 import문 이후에 사용할 모듈의 별칭

In [39]:
import pandas as pd
import numpy as np

- np의 np.arange(10, 22)는 10부터 21까지의 숫자발생
- reshape(3, 4)는 최초 생성된 1행 12열 자리 (10~21) 모양을 3행 4열로 변경

In [40]:
a = np.arange(10, 22)
# numpy의 arange의 결과는 리스트가 아니라 1행 12열짜리 행렬로 리턴됩니다.
print(a)

b = a.reshape(3, 4) # 실행결과는 3행 4열짜리 행렬
print(b)

c = np.arange(10, 22).reshape(3, 4)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


- pandas의 DataFrame: 행과 열로 이루어져있는 판다스의 대표적 2차원 데이터 구조
- index는 행번호에 사용할 요소를 리스트로 입력받는 요소
- columns는 열제목으로 사용할 요소를 리스트로 입력받는 요소
- 한개의 열을 의미하는 Series들이 모여 만들어진 구조입니다.
- pandas의 Series: 한개의 열이름과 다수의 값들이 존재하는 1차원 데이터 구조

In [50]:
df = pd.DataFrame(b, index=["a", "b", "c"], columns=["A", "B", "C", "D"])
print(df)

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21


In [51]:
# 행이름으로 행을 필터링
# loc는 []와 함께 사용되는 행 지정 명령
# 아래와 같이 사용하면 인덱스 'a'행의 내용을 컬럼이름과 함게 보여준다
# 마지막행에 인덱스의 이름과 자리를 차지하고 있는 데이터의 자료형을 출력합니다.
# int32는 32비트(4바이트)형 정수
print(df.loc['a'])

A    10
B    11
C    12
D    13
Name: a, dtype: int32


In [52]:
# 열이름으로 열을 필터링
# 열의 필터링은 이미 Series단위로 구분되어 있는 열을 필터링하기때문에
# 아래와 같이 loc없이 열이름만 표현합니다.
print(df['A'])

a    10
b    14
c    18
Name: A, dtype: int32


In [53]:
# 슬라이싱 한 인덱스 적용
# 두개 이상의 인덱스 표현부터 세로로 출력안하고 원래의 표현식을 갖춰서 출력
print(df.loc["b":"c"])

    A   B   C   D
b  14  15  16  17
c  18  19  20  21


In [71]:
# "B"부터 끝까지의 열
print(df["B":])
print()
# 행의 검색은 index값으로 검색하고, 열들의 검색은 열의 제목
# 따라서 열의 검색은 슬라이싱으로 적용하지않고, 값에 의한 비교로 주로 적용합니다.

print(df[df["A"] >= 11])
# 열의 제목중 제외하고 싶은 내용은 drop을 이용하여 따로 연산한 결과를 얻거나
# 표시하고자 하는 열제목만 지목하여 필터링합니다.

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

    A   B   C   D
b  14  15  16  17
c  18  19  20  21
